### PR TITLE
Update endpoints libs

### PR DESCRIPTION
**Pull request by OlegYch**

### CODE REVIEW

**Comment by OlegYch** [comment]
@julienrf can you please release

**Comment by julienrf** [comment]
@OlegYch Thank you for the maintenance work! I think you should have enough rights to cut the release here: https://github.com/endpoints4s/play/releases (I guess the version should be 7.0.0 since we bumped the openapi module). Could you please confirm?

**Comment by OlegYch** [comment]
@julienrf yep it seems to have worked

**Comment by OlegYch** [comment]
@julienrf actually it looks like it failed
```
> ci-release
No access to secret variables, doing nothing
```

**Comment by julienrf** [comment]
I am not sure what’s going wrong :-/

This message is printed if the sbt-ci-release plugin estimates that the execution environment is not “secure”. In our case, this condition should be `true`:

https://github.com/sbt/sbt-ci-release/blob/4415c89701c38c96711138d5e115a0fd5985f2ef/plugin/src/main/scala/com/geirsson/CiReleasePlugin.scala#L32

Could you please investigate the issue? Feel free to re-create a GPG key pair if necessary…

Also FYI I removed your last commit that resets the compatibility intention. We can re-apply it after the release works.

**Comment by OlegYch** [comment]
@julienrf i don't have access to repository secrets

**Comment by julienrf** [comment]
Could you please retry now?

**Comment by OlegYch** [comment]
@julienrf the problem was with passing env vars to sbt, i fixed it
but i messed up the secrets (although they might have been messed up before that) so someone with permission to publish to endpoints4s on central will need to update SONATYPE (and possibly PGP) secrets

**Comment by julienrf** [comment]
Thank you for fixing those issues! I’ve reset the Sonatype credentials and re-launched the job…

**Comment by OlegYch** [comment]
@julienrf cheers, it worked

**Pull request merged**
