### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by julienrf**

### CODE REVIEW

**Comment by OlegYch** [comment]
@julienrf can you please cut a release?

**Comment by julienrf** [comment]
Yes: https://github.com/endpoints4s/play/releases/tag/v6.0.0

**Comment by julienrf** [comment]
BTW, do you have access to publishing new releases from the GitHub UI? https://github.com/endpoints4s/play/releases/new

**Comment by OlegYch** [comment]
ah, great, thanks!
for some reason it isn't listed on central 
image

**Comment by OlegYch** [comment]
@julienrf yep i have the access, thanks!

**Comment by julienrf** [comment]
> for some reason it isn't listed on central

Hum, that’s weird :-/

It is there, though: https://repo1.maven.org/maven2/org/endpoints4s/play-server_2.13/6.0.0/

I hope everything is right.

**Comment by OlegYch** [comment]
yep, it works

**Pull request merged**
